services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: george-server
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=192.168.0.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
    volumes:
      - ./state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
