services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
      - LIBVA_DRIVER_NAME=i965
    volumes:
      - ./config:/config
      - /mnt/data_1tb/media/movies:/data/movies
      - /mnt/data_1tb/media/tv:/data/tvshows
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "992"
    restart: unless-stopped
