services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
      - VERSION=docker
    volumes:
      - /home/george/plex/config:/config
      - /mnt/data_1tb/media/movies:/movies
      - /mnt/data_1tb/media/tv:/tv
    restart: unless-stopped